$(document).ready(function(){
	$("#inp1").click(function(){
		$("#newsa").hide();
		$("#newsb").hide();
		$("#newsc").hide();
		$("#newsd").hide();
		$(this).parent().parent().parent().find('#news').eq(0).show();
	});
	$("#inp2").click(function(){
		$("#news").hide();
		$("#newsb").hide();
		$("#newsc").hide();
		$("#newsd").hide();
		$(this).parent().parent().parent().find('#newsa').eq(0).show();
	});
	$("#inp3").click(function(){
		$("#newsa").hide();
		$("#news").hide();
		$("#newsc").hide();
		$("#newsd").hide();
		$(this).parent().parent().parent().find('#newsb').eq(0).show();
	});
	$("#inp4").click(function(){
		$("#news").hide();
		$("#newsa").hide();
		$("#newsb").hide();
		$("#newsd").hide();
		$(this).parent().parent().parent().find('#newsc').eq(0).show();
	});
	$("#inp5").click(function(){
		$("#newsa").hide();
		$("#news").hide();
		$("#newsb").hide();
		$("#newsc").hide();
		$(this).parent().parent().parent().find('#newsd').eq(0).show();
	});
});